Arch:
  input_dim: 1
  name: enet
  num_classes: 2
Constraints:
  confident: false
Data:
  labeled_data_ratio: 0.99
  seed: 1
  unlabeled_data_ratio: 0.01
DataLoader:
  labeled_batch_size: 4
  num_workers: 0
  shuffle: true
  unlabeled_batch_size: 4
  val_batch_size: 6
Dataset: acdc
Optim:
  lr: 0.0001
  name: RAdam
  weight_decay: 0.0005
RegScheduler:
  begin_epoch: 5
  max_epoch: 50
  max_value: 0.001
RegScheduler1:
  begin_epoch: 5
  max_epoch: 50
  max_value: 0.001
Scheduler:
  T_max: 90
  name: CosineAnnealingLR
  warmup:
    multiplier: 300
    total_epoch: 10
Train_vat: false
Trainer:
  device: cpu
  max_epoch: 100
  num_batches: 200
  save_dir: tmp
seed: 123
